---
title: "Order of Sound Changes"
author: Thomas W. Broadwater
mainfont: Brill
header-includes:
   - \usepackage{phonrule, amsmath}
output:
  pdf_document:
    latex_engine: xelatex
  html_document: default
---

# Initial Notes



## The Oxford Introduction to Proto-Indo-European and the Proto-Indo-European World

-  Mallory and Adams kindly provided my least favorite table ever
  -  Vowels are implied to be consonants? I know they're not, but the table seems to think so
  -  No mention of syllabic consonants
  -  What the actual *heck* does *r/3* mean???
      -  I wonder if this isn't an encoding error...

|             | Unvoiced | Voiced | Voiced Aspirate |
|-------------|----------|--------|-----------------|
| Labials     | p        | b      | bh              |
| Dentals     | t        | d      | dh              |
| Palatals    | k        | g      | gh              |
| Velars      | k        | g      | gh              |
| Labiovelars | kʷ       | gʷ     | ghʷ             |
| Sibilants   | s        |        |                 |
| Laryngeals  | h₁       | h₂     | h₃ & h₄         |
| Liquids     | r/3      | l/C    |                 |
| Nasals      | m/i      | n/     |                 |
| Semivowels  | i/y      | u/w    |                 |
| Vowels      | e        | o      | a               |
|             | ē        | ō      | ā               |

-  Laryngeal consonants affect the adjacent vowel
  - *\*h₁* has no affect
  - *\*h₂* and *\*h₄* change *\*-e-* to *\*-a-*
    -  Only distinguishable following two conditions:
        -  Word initial
        -  Reflex attested in Anatolian
    -  If they can't be distinguished, they are annotated as *\*hₐ*
  -  *\*h₃* changes *\*-o-* to *\*-e-*
-  If we suspect a laryngeal but can't identify it, it is annotated as *\*hₓ*

-  I'm going to try and edit this table

|             | Unvoiced | Voiced  | Voiced Aspirate |
|-------------|----------|---------|-----------------|
| Labials     | p        | b       | bh              |
| Dentals     | t        | d       | dh              |
| Palatals    | kʲ       | gʲ      | ghʲ             |
| Velars      | k        | g       | gh              |
| Labiovelars | kʷ       | gʷ      | ghʷ             |
| Sibilants   | s        |         |                 |
| Laryngeals  | h₁       | h₂      | h₃ & h₄         |
| Liquids     | r/r̥      | l/l̥     |                 |
| Nasals      | m/m̥      | n/n̥     |                 |
| Semivowels  | i/y (i̯)  | u/w (u̯) |                 |
| Vowels      | e        | o       | a               |
|             | ē        | ō       | ā               |

-  Ablaut sucks

| Long | Short | Zero |
|------|-------|------|
| e    | o     | ∅    |
| ē    | ō     | ∅    |
| ehₓ | ohₓ   | ∅hₓ  |


## New Comparative Grammar of Greek and Latin

### Short Vowels

PIE \*i and \*u were incredibly well behaved, and largely retained their
qualities in G.

\[
  \phon{\mathrm{*i}}{\mathrm{ι}}
\]

\[
  \phon{\mathrm{*u}}{\mathrm{υ}}
\]

There is possibly a word-initial reflex for \*HV segments, though the data
is inconclusive.

\[
  \phonl{*\mathrm{h\textsubscript{1}u}}{\mathrm{ευ}}{\#}
\]

\[
  \phonl{*\mathrm{h\textsubscript{2}u}}{\mathrm{αυ}}{\#}
\]

The vowel \*e and the segment \*h₁e have identical reflexes in G, and are
difficult to distinguish w/o looking for evidence in other language families.

\[
  \phon
    {
      \left.
      \begin{matrix}
        \mathrm{*e} \\
        \mathrm{*h\textsubscript{1}e}
      \end{matrix}
      \right\}
    }
    {
      \mathrm{ε}
    }
\]

\*e may have become \*o in "strongly labial environment[s]."
This is not explained any futher.

\[
  \phonb{\mathrm{\*e}}{\mathrm{\*o}}{\mathrm{¿}~}{~\mathrm{?}}
\]

The prefix \*en- may have returned ἰγ- (/ing/),
though this is poorly evidenced.

A *lot* of vowels returned G ο.

\[
  \phon
    {
      \left.
      \begin{matrix}
        \mathrm{o} \\
        \mathrm{h\textsubscript{2}o} \\
        \mathrm{h\textsubscript{3}o} \\
        \mathrm{h\textsubscript{3}e}
      \end{matrix}
      \right\}
    }
    {o}
\]

